### ISSUE TITLE
Ouroboros using Universal Time instead of local

### ISSUE THREAD

**Issue by kamilmirza** [gmt2001/ouroboros#27]
as per title I am getting wrong time in container logs and notifications
have tried mounting ```/etc/timezone:/etc/timezone:ro``` & ```/etc/localtime:/etc/localtime:ro``` but to no gain

**Comment by gmt2001** [comment]
Looks like the emails are hard coded to UTC. The logger is the default Python logger which is supposed to use the same timezone as the os environment

I will try to look into changing this to be configurable via the Docker Environment Variables

**Comment by gmt2001** [comment]
I just double-checked and the Timezone configuration shown in the [Wiki](https://github.com/gmt2001/ouroboros/wiki/Timezone-Configuration) and the [Docker Compose](https://github.com/gmt2001/ouroboros/blob/main/docker-compose.yml) file work correctly

**Comment by kamilmirza** [comment]
I am using correct `TZ` in my `docker-compose` file:
```
  ouroboros:
    container_name: ouroboros
    hostname: XYZ
    image: gmt2001/ouroboros
    network_mode: host
    environment:
      - CLEANUP=true
      - CRON=0 6 */2 * * # every second day of the week @ 6AM
      - LOG_LEVEL=info # debug info warn error critical
      - SELF_UPDATE=true
      - NOTIFIERS=tgram://BOT
      - TZ=Asia/Karachi
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
here's the ouroboros docker log:
```
2021-06-14 08:29:35 : INFO : ouroboros : Version: 1.7.0-main
2021-06-14 08:29:35 : INFO : config : Cron configuration is valid. Using Cron schedule ['0', '6', '*/2', '*', '*']
2021-06-14 08:29:36 : INFO : asyncio : Notifying 1 service(s) asynchronously.
2021-06-14 08:29:36 : INFO : NotifyTelegram : Sent Telegram notification.
```
```
$ timedatectl
               Local time: Mon 2021-06-14 13:30:03 PKT
           Universal time: Mon 2021-06-14 08:30:03 UTC
```
and here's my telegram bot notification:
![ApplicationFrameHost_2021-06-14_13-31-13](https://user-images.githubusercontent.com/6561475/121863075-e6ca7500-cd14-11eb-8208-8d6a545e7db0.png)
you can clearly see the difference in Time and message Received Time
