### ISSUE TITLE
ouroboros fails to upgrade my homeassistant container at least on a really slow IO box

### ISSUE THREAD

**Issue by prahal** [gmt2001/ouroboros#69]
ouroboros fails to upgrade my homeassistant container on a really slow IO box (ie very busy one, the initial dovecot FTS indexing proceeds for months).

I missed the time to try tweaking the code (I switched to watchtower today but still have to see on new homeassistant image update if it also timeout on this box). But could be that it is simply a matter of making the timeout an environment variable that I could tweak (it seems it defaults to 60 seconds).

At least this bug report might service as a clue to another user with the same error.

The homeassistant image is 1.8GB.

gmt2001/ouroboros:latest
from 2023-03-24 23:04:42
sha256:d563375caa178b8e1106b268e26934e5bb9c0d13456d973617e47d7a1666c364

I get this error:
```
2023-08-15 21:45:32 : INFO : dockerclient : homeassistant will be updated
15/08/2023 21:45:32
2023-08-15 21:45:32 : DEBUG : dockerclient : Stopping container: homeassistant
15/08/2023 21:45:55
2023-08-15 21:45:55 : DEBUG : connectionpool : http://localhost:None "POST /v1.41/containers/d86318fd7f92cf69084b2a69503f801b76cff328b7563deb9d6ad8e1bd5c99f7/stop HTTP/1.1" 204 0
15/08/2023 21:45:55
2023-08-15 21:45:55 : DEBUG : dockerclient : Removing container: homeassistant
15/08/2023 21:46:57
2023-08-15 21:46:56 : ERROR : base : Job "Initial run interval container update for unix://var/run/docker.sock (trigger: date[2023-08-15 21:33:53 CEST], next run at: 2023-08-15 21:33:53 CEST)" raised an exception
15/08/2023 21:46:57
Traceback (most recent call last):
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 449, in _make_request
15/08/2023 21:46:57
    six.raise_from(e, None)
15/08/2023 21:46:57
  File "<string>", line 3, in raise_from
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 444, in _make_request
15/08/2023 21:46:57
    httplib_response = conn.getresponse()
15/08/2023 21:46:57
                       ^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/http/client.py", line 1374, in getresponse
15/08/2023 21:46:57
    response.begin()
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/http/client.py", line 318, in begin
15/08/2023 21:46:57
    version, status, reason = self._read_status()
15/08/2023 21:46:57
                              ^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/http/client.py", line 279, in _read_status
15/08/2023 21:46:57
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
15/08/2023 21:46:57
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/socket.py", line 706, in readinto
15/08/2023 21:46:57
    return self._sock.recv_into(b)
15/08/2023 21:46:57
           ^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
TimeoutError: timed out
15/08/2023 21:46:57
15/08/2023 21:46:57
During handling of the above exception, another exception occurred:
15/08/2023 21:46:57
15/08/2023 21:46:57
Traceback (most recent call last):
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
15/08/2023 21:46:57
    resp = conn.urlopen(
15/08/2023 21:46:57
           ^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
15/08/2023 21:46:57
    retries = retries.increment(
15/08/2023 21:46:57
              ^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 550, in increment
15/08/2023 21:46:57
    raise six.reraise(type(error), error, _stacktrace)
15/08/2023 21:46:57
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/urllib3/packages/six.py", line 770, in reraise
15/08/2023 21:46:57
    raise value
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
15/08/2023 21:46:57
    httplib_response = self._make_request(
15/08/2023 21:46:57
                       ^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 451, in _make_request
15/08/2023 21:46:57
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout
15/08/2023 21:46:57
    raise ReadTimeoutError(
15/08/2023 21:46:57
urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
15/08/2023 21:46:57
15/08/2023 21:46:57
During handling of the above exception, another exception occurred:
15/08/2023 21:46:57
15/08/2023 21:46:57
Traceback (most recent call last):
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
15/08/2023 21:46:57
    retval = job.func(*job.args, **job.kwargs)
15/08/2023 21:46:57
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/pyouroboros/dockerclient.py", line 369, in update
15/08/2023 21:46:57
    new_container = self.recreate(container, latest_image)
15/08/2023 21:46:57
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/pyouroboros/dockerclient.py", line 137, in recreate
15/08/2023 21:46:57
    self.remove(container)
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/pyouroboros/dockerclient.py", line 128, in remove
15/08/2023 21:46:57
    container.remove()
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/docker/models/containers.py", line 352, in remove
15/08/2023 21:46:57
    return self.client.api.remove_container(self.id, **kwargs)
15/08/2023 21:46:57
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/docker/utils/decorators.py", line 19, in wrapped
15/08/2023 21:46:57
    return f(self, resource_id, *args, **kwargs)
15/08/2023 21:46:57
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/docker/api/container.py", line 1024, in remove_container
15/08/2023 21:46:57
    res = self._delete(
15/08/2023 21:46:57
          ^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/docker/utils/decorators.py", line 46, in inner
15/08/2023 21:46:57
    return f(self, *args, **kwargs)
15/08/2023 21:46:57
           ^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/docker/api/client.py", line 245, in _delete
15/08/2023 21:46:57
    return self.delete(url, **self._set_request_timeout(kwargs))
15/08/2023 21:46:57
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 669, in delete
15/08/2023 21:46:57
    return self.request("DELETE", url, **kwargs)
15/08/2023 21:46:57
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
15/08/2023 21:46:57
    resp = self.send(prep, **send_kwargs)
15/08/2023 21:46:57
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
15/08/2023 21:46:57
    r = adapter.send(request, **kwargs)
15/08/2023 21:46:57
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
15/08/2023 21:46:57
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 578, in send
15/08/2023 21:46:57
    raise ReadTimeout(e, request=request)
15/08/2023 21:46:57
requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
16/08/2023 21:33:54
```

the ouroborous portainer stack was:
```
version: '2'
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: gmt2001/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=86400
      - LOG_LEVEL=debug
      - SELF_UPDATE=true
      - IGNORE=
      - TZ=Europe/Paris
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

the homeasstant on is:
```
version: '3.8'

services:
  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - PUID=1002 # Enter the UID of the user who should own the files here
      - PGID=100  # Enter the GID of the user who should own the files here
      - TZ=Europe/Paris # Enter your timezone
    volumes:
      - /srv/dev-disk-by-label-secure/appdata/docker/homeassistant:/config
      - /etc/pki/realms/prahal.homelinux.net:/etc/pki/realms/prahal.homelinux.net:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    ports:
      - 8123:8123
    devices:
      - "/dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0:/dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0"
      - "/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0KWPMU-if00-port0:/dev/serial/by-id/usb-FTDI_FT232R_USB_UART_AB0KWPMU-if00-port0"
```
