### ISSUE TITLE
Issue detecting image tag for all containers

### ISSUE THREAD

**Issue by Qhilm** [gmt2001/ouroboros#80]
Hello,

I get this type of errors in the log:

`2023-12-14 10:32:34 : ERROR : dockerclient : Issue detecting portainer's image tag. Skipping...`

It does that seemingly for all my containers, even for itself.

I had previously pyouroboros/ouroboros, it was working fine but since it's not maintained at all anymore, I thought of switching before it finally breaks.

I must have done some very basic mistake somewhere, but I cannot figure it out.

Docker Compose:

```yaml
version: '3'
services:
  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: ghcr.io/gmt2001/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      - IGNORE=nextcloud-aio-mastercontainer nextcloud-aio-notify-push nextcloud-aio-apache nextcloud-aio-nextcloud nextcloud-aio-imaginary nextcloud-aio-docker-socket-proxy nextcloud-aio-fulltextsearch nextcloud-aio-clamav nextcloud-aio-redis nextcloud-aio-database
      - TZ=Europe/Amsterdam
      - LANGUAGE=en
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/ouroboros/hooks:/app/pyouroboros/hooks # https://github.com/gmt2001/ouroboros/wiki/Hooks
```

Docker 20.10.23
DSM 7.2
